{% set name = "json_stream" %}
{% set version = "2.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 25e85e144eb15a72f5039ca28ec289a2a9821ea78a4e465811386fc5a9f3fb7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }},<4.0
    - json-stream-rs-tokenizer >=0.4.17

test:
  imports:
    - json_stream
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Streaming JSON encoder and decoder
  home: https://github.com/daggaz/json-stream
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
